---
name: CI/CD
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.sh'
      - '**.txt'
  schedule:
    - cron: '0 18 * * 0'
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.sh'
      - '**.txt'
 
jobs:
  test_and_build:
    runs-on: self-hosted
    name: Code check and build container, no push
    if: github.event_name == 'pull_request'
    strategy:
      matrix:
        os: [ ubuntu2004, ubuntu2204, centos7 ]
    steps:
      - name: Checkput the codebase
        uses: actions/checkout@v3

      - name: Hadolint
        uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: ${{ matrix.os }}/Dockerfile
          ignore: SC2086, DL3008, DL3013, DL3002, DL3007, DL3018, DL3033, SC3037, DL3059, SC2039

      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses:  docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build image.
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ${{ matrix.os }}/Dockerfile
          platforms: linux/amd64
          push: false
          tags: ${{ github.repository }}:latest

  build_container:
    name: Build container based on matrix
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'
    strategy:
      matrix:
        os: [ ubuntu2004, ubuntu2004, centos7 ]
    steps:
      - name: Checkput the codebase
        uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses:  docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push image.
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ${{ matrix.os }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ github.repository }}:latest
